// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSu8rZ8g0ituqlIsQPtDUeLJ2KC92ZZaQ',
    appId: '1:138916081860:ios:b16f1418dc2b269b115991',
    messagingSenderId: '138916081860',
    projectId: 'recipe-app-b1ddb',
    storageBucket: 'recipe-app-b1ddb.firebasestorage.app',
    iosBundleId: 'com.example.cb015714',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSu8rZ8g0ituqlIsQPtDUeLJ2KC92ZZaQ',
    appId: '1:138916081860:ios:b16f1418dc2b269b115991',
    messagingSenderId: '138916081860',
    projectId: 'recipe-app-b1ddb',
    storageBucket: 'recipe-app-b1ddb.firebasestorage.app',
    iosBundleId: 'com.example.cb015714',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOQ6UuZXFN7BYxPnd4WqgsuHzOY_iSHeg',
    appId: '1:138916081860:web:814bba0c6db8c09a115991',
    messagingSenderId: '138916081860',
    projectId: 'recipe-app-b1ddb',
    authDomain: 'recipe-app-b1ddb.firebaseapp.com',
    storageBucket: 'recipe-app-b1ddb.firebasestorage.app',
    measurementId: 'G-7Y43YKE0SB',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQ6UuZXFN7BYxPnd4WqgsuHzOY_iSHeg',
    appId: '1:138916081860:web:814bba0c6db8c09a115991',
    messagingSenderId: '138916081860',
    projectId: 'recipe-app-b1ddb',
    authDomain: 'recipe-app-b1ddb.firebaseapp.com',
    storageBucket: 'recipe-app-b1ddb.firebasestorage.app',
    measurementId: 'G-7Y43YKE0SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuCg5Dg9hYWQhFlHfs1OScxs1oZGzv0js',
    appId: '1:138916081860:android:9c79d371f7c2e664115991',
    messagingSenderId: '138916081860',
    projectId: 'recipe-app-b1ddb',
    storageBucket: 'recipe-app-b1ddb.firebasestorage.app',
  );
}
